### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by dlt** [InstaPy/InstaPy#150]
I'm getting the following error:

> Traceback (most recent call last):
>   File "script.py", line 10, in <module>
>     session.like_by_tags(['fitness'], amount=100)
>   File "/Users/dlt/programming/python/InstaPy/instapy/instapy.py", line 271, in like_by_tags
>     self.username, self.like_by_followers_upper_limit, self.like_by_followers_lower_limit)
> TypeError: 'NoneType' object is not iterable

when I try to run the following InstaPy script:

```python
InstaPy(username='XXX', password='XXX')\
  .login()\
  .set_do_comment(True, percentage=10)\
  .set_comments(['Cool!', 'Awesome!', 'Nice!'])\
  .set_dont_include(['friend1', 'friend2', 'friend3'])\
  .set_dont_like(['girl', 'hot'])\
  .set_ignore_if_contains(['pizza'])\
  .like_by_tags(['fitness'], amount=10)\
  .end()

**Comment by blesson3** [comment]
Are you up to date on the latest commit?
I had this same issue earlier after PR #132 but was fixed since in the last couple of commits

**Comment by eduardocalazansjr** [comment]
For some users it won't work.
Wait for a fix.

**Comment by razvanilin** [comment]
For me it works if I checkout the #132 PR. Also, this issue should still be open until it gets fixed.

**Comment by pekapa** [comment]
@razvanilin, it was fixed last night. I've made a direct commit to solve it, try updating to the latest version.

**Comment by eduardocalazansjr** [comment]
On some/all business accounts it wouldn't work yet.
As i said, wait for a fix (soon)

@razvanilin thanks, i will reopen this issue and when i'm done fixing this will keep everyone updated.

**Comment by eduardocalazansjr** [comment]
The issues that is related with this issue are:

#134 
#146 
#149 
#152 

All of that still happens for some accounts, still working on it.
