### ISSUE TITLE
Unfollow script not working (Showing browser output instead?)

### ISSUE THREAD

**Issue by neonvandal** [InstaPy/InstaPy#1875]
Hello everyone, 
I'm having issues when trying to begin the unfollow part of the script.
Everything else is working as expected.
When the unfollow tries to start there seems to be an error on which instead it shows the browser output.

My config:

 session = InstaPy(username=insta_username,
                  password=insta_password,
                  headless_browser=False,
                  multi_logs=True)

try:
    session.login()

    # settings
    session.set_upper_follower_count(limit=2000)
    session.set_do_comment(True, percentage=20)
    session.set_do_follow(enabled=True, percentage=50, times=1)
    session.set_comments([u'Nice!!', u' Greattt :)', u'Awesome! :heart:'], media=None)
    session.like_by_tags(['xx', 'xx', 'xxxx', 'xxx'], amount=70, media=None)
    #session.unfollow_users(amount=150, onlyInstapyFollowed = True, onlyInstapyMethod = 'FIFO', sleep_delay=120)
    #session.set_dont_unfollow_active_users(enabled=True, posts=5, boundary=None)
    session.unfollow_users(amount=10, onlyNotFollowMe=True, sleep_delay=60)

I'm aware that the Onlynotfollowme task can't be along with the onlyinstapyfollowed, that's why I commented the other 2 lines in this case.
But I tried all options and runned the script with different configs (OnlyInstapyFollowed, Dont unfollow active user, those 2, only one, etc) and the unfollow action just keeps showing this:

![unfollow issues](https://user-images.githubusercontent.com/38476899/38896224-7c837e74-4268-11e8-892d-fa9168426f67.png)
and later an'Oops an error occurred' message.

Any ideas?

Thanks in advance!!

**Comment by CharlesCCC** [comment]
fixed with latest version. make sure you update it

**Comment by neonvandal** [comment]
Hello @CharlesCCC  ! It is still happening on my side, I got the latest changes :/

**Comment by neonvandal** [comment]
This is the url on which the same issue mentioned above is happening now, I don't know if this is useful but: https://www.instagram.com/graphql/query/?query_hash=37479f2b8209594dde7facb0d904896a&variables={%22id%22:%20%22209881264%22,%20%22first%22:%2050,%20%22after%22:%20%22AQDhfZKG30wwn9SiOeAEcbMYFyERvA9M6iZ47EwFJ9FqsJEW2W3x1SX2Gr7k8tRqwW5PyRzC7f7oPkXc-f9CYnBeSupdnNA2OZJ1-Nq51y2vhA%22}

**Comment by CharlesCCC** [comment]
@neonvandal how did you updated your version ? can you do a `git log` and copy paste here.

**Comment by neonvandal** [comment]
@CharlesCCC Hello Charles! Sorry for the delay. To be honest I didn't fully understood how to get latest on Github. What I'm currently doing is : 
Go to Github
Current Branch: Master
Press Fetch
Wait for it to finish
Then do a Pull

I assume that there are a lot of chances that this is not the correct way to do it, but with previous changes it worked.

Can you help me out?

Thanks in advance!!

Cheers
