### ISSUE TITLE
Unfollow Issue

### ISSUE THREAD

**Issue by cormo1990** [InstaPy/InstaPy#1964]
Anyone with the same error?

![unfollow_issue](https://user-images.githubusercontent.com/36590321/39619813-5f3fbd68-4f89-11e8-884a-85ff508b7d0e.png)

**Comment by lvkins** [comment]
Yep. Unfortunately having this issue as well.

**Comment by lvkins** [comment]
Have digged into this. This can be caused by possible usage of `session.set_sleep_reduce`.

@timgrossmann @uluQulu 

Should we consider setting a rough sleep time not affected by `session.set_sleep_reduce` inside unfollow loop to prevent the bot being blocked?

**Comment by uluQulu** [comment]
@pompex,
Good idea, can you implement it?

**Comment by cormo1990** [comment]
Up...any updates friends?

**Comment by uluQulu** [comment]
Hi @cormo1990 
I have implemented some set of features which also touch unfollow definitions and if you explain the issue in details, I can help you solve it, too!

**Comment by cormo1990** [comment]
@uluQulu Thanks for your answer mate, i can't explain well what happened...sometimes i have the error showed in first post...but i didn't change anything...i ll let you know if happen again and if i understand the problem

**Comment by cormo1990** [comment]
@uluQulu The problem persists and I don't know how to fix it and give you further helpful information... :(

**Comment by uluQulu** [comment]
I think understood you, @cormo1990 
Last days I used unfollow feature after a long time and I think you mean the notation of
_`yourusername` might be blocked_

You are right about it be not so understandable notation and it says that, after clicking on unfollow button, and then re-checking that button to see if it is either `Follow` or `Follow Back` to verify that unfollow did happen.
And once it still is `Unfollow`, it means your account prob was temporarily blocked from unfollowing. So at that moment the program ends the unfollow feature.

Also there can be other reasons to it else than temporary block, and it must be investigated further.
_e.g. sometimes button clicks take time to accomplish and the re-check time might be short, etc._

How do you think to improve it, any idea?
_e.g. adding a sleep delay after that time instead of breaking the unfollow activity can be an option, so that you can continue to unfollow after possible temporary block._

**Comment by cormo1990** [comment]
@uluQulu yes, it is possible, but i suppose that it isn't a temporarily block because if i restart immediatly the unfollow action it run, sometimes it appears the same error after around 100 unfollowed user sometimes not...

**Comment by ArdySan2012** [comment]
@cormo1990 @uluQulu Does it work for you now? I get this error, even though the unfollow is not blocked ...

**Comment by cormo1990** [comment]
@ArdySan2012 hi friend, I suppose that is a safe check in order to avoid to be blocked.
I check that if I use unfollow task for a lot works good but if I follow accounts and after 2 hours I defollow for example the issue remain....so my suggestion for the moment is to have Long run of follow and long run of defollow.

with another account I'm using the latest release and I don't have this problem so another solution is update your files with the latest

**Comment by ArdySan2012** [comment]
I see, thank you!

**Comment by dbmathis** [comment]
Started seeing this issue today. 

Using these settings: `session.unfollow_users(amount=60, InstapyFollowed=(True, "nonfollowers"), style="FIFO", unfollow_after=6*60*60, sleep_delay=501)`

**Comment by cormo1990** [comment]
any update friends? this issue persists and now in my case happen everytime i start unfollow action

**Comment by ghost** [comment]
i notice that also.

My problem was the variable "dont_include"; was filled with all the users so the unfollow doesn't unfollow anyone ... 

i solved it by not use

```
session.set_dont_include()
session.set_ignore_users()
```

cheers.

**Comment by cormo1990** [comment]
it doesn't work friend...

@uluQulu can you help me please? from this morning i can't unfollow user, the message is always that i am blocked but it isn't true...

**Comment by dbmathis** [comment]
A bit more info. I am managing two accounts and seeing the same for both. With both accounts, I am able to unfollow through Instagram itself.

```
INFO [2018-07-03 10:06:48] [XX]  Not unfollowing 'YY'!  ~user is in the whitelist

ERROR [2018-07-03 10:06:55] [XX  Unfollow error!  ~username XX might be blocked
```
