### ISSUE TITLE
Less users to follow than requested. == 312

### ISSUE THREAD

**Issue by S4nderr** [InstaPy/InstaPy#2056]
## Expected Behavior
session.interact_user_followers(['djkhaled'], amount=1000, randomize=True)
## Current Behavior
WARNING [2018-05-19 14:37:26] [sendergrem]  diazandbruno -> Less users to follow than requested. == 312

The account has more than millions of followers why is it puttin out less users == 312?

**Comment by uluQulu** [comment]
Hi @S4nderr,
Pull latest files, it should be fixed.

**Comment by S4nderr** [comment]
I have downloaded the lastest files and I am still getting the error, any clue..?

Also, is it possible to keep track of the profiles I have given likes to so that next time I start its not going to like photos from the same profile again

**Comment by uluQulu** [comment]
@S4nderr,
Post the console output of that error.
Blacklist campaigns are just for that reason, to use, add this to your quickstart script,
```erlang
session.set_blacklist(enabled=True, campaign='Memorizer')
```
_Unless you change campaign from `Memorizer` to sth else, it will not interact on the same person again. (see `README` for more information)_

**Comment by aleeepp** [comment]
Hello, I have the same error , I few week ago I used this to solve something similar [link](https://github.com/timgrossmann/InstaPy/issues/1548), and its work for a week but I had a problem with a CPU and Memory usage creeping up, because that I download the latest file but now i am in the same problem i think than the beginning.

This is my config, what can i do, I run this  10 time in the same day every day.

`
insta_username = 'aaaaaaaaaaa'
    insta_password = 'aaaaaaaaaaaaaa'

    session = InstaPy(username=insta_username,
                      password=insta_password,
                      headless_browser=False,
                      multi_logs=True)

    try:
        session.login()

        # settings
        session.set_relationship_bounds(enabled=False,
    				 potency_ratio=0.9,
    				  delimit_by_numbers=True,
    				   max_followers=6000,
    				    max_following=6000,
    				     min_followers=2,
    				      min_following=2)
        session.set_do_comment(False, percentage=10)
        session.set_ignore_users(['aaaaaaaaaa'])
        session.set_dont_include(['aaaaaaaaaa'])

        # actions
        session.follow_user_followers(['aaaaaaaa'], amount=29, randomize=True, sleep_delay=301)

    except Exception as exc:
        # if changes to IG layout, upload the file to help us locate the change
        if isinstance(exc, NoSuchElementException):
            file_path = os.path.join(gettempdir(), '{}.html'.format(time.strftime('%Y%m%d-%H%M%S')))
            with open(file_path, 'wb') as fp:
                fp.write(session.browser.page_source.encode('utf8'))
            print('{0}\nIf raising an issue, please also upload the file located at:\n{1}\n{0}'.format(
                '*' * 70, file_path))
        # full stacktrace when raising Github issue
        raise

    finally:
        # end the bot session
        session.end()`
