### ISSUE TITLE
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(@class,'_t98z6')]//span"}

### ISSUE THREAD

**Issue by Foerdy** [InstaPy/InstaPy#2158]
When I use the `session.set_dont_unfollow_active_users` setting, I get the following error:

Traceback (most recent call last):
  File "./quickstart.py", line 39, in <module>
    session.set_dont_unfollow_active_users(enabled=True, posts=10)
  File "/home/foerdy/InstaPy/instapy/instapy.py", line 2357, in set_dont_unfollow_active_users
    self.logger)
  File "/home/foerdy/InstaPy/instapy/util.py", line 202, in get_active_users
    "//span[contains(@class,'_t98z6')]//span").text)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 293, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 752, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[contains(@class,'_t98z6')]//span"}
  (Session info: chrome=67.0.3396.62)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Linux 4.15.0-22-generic x86_64)

**Comment by uluQulu** [comment]
Hi @Foerdy 
It already is solved.
Have a look at #2136 for compiled solution **or** see #2131 to manually apply those fixes (_https://github.com/timgrossmann/InstaPy/issues/2131#issuecomment-393531365, https://github.com/timgrossmann/InstaPy/issues/2131#issuecomment-393550848 and https://github.com/timgrossmann/InstaPy/issues/2131#issuecomment-393567856_)

Cheers

**Comment by arsayu** [comment]
I tried and still not working.
DevTools listening on ws://127.0.0.1:12752/devtools/browser/6f82a19c-8087-408c-880f-b45d1a17122c
INFO [2018-06-02 23:42:19] [moj.gram]  Session started - 2018-06-02 23:42:19
WARNING [2018-06-02 23:42:19] [moj.gram]  Sorry, Record Activity is not working on Windows. We're working to fix this so
on!
Cookie file not found, creating cookie...
**********************************************************************
If raising an issue, please also upload the file located at:
C:\Users\vortex\AppData\Local\Temp\20180602-234252.html
**********************************************************************
[3636:5016:0602/234252.515:ERROR:gles2_cmd_decoder.cc(16126)] Context lost because SwapBuffers failed.
[3636:5016:0602/234252.516:ERROR:gles2_cmd_decoder.cc(5637)] Error: 5 for Command kPostSubBufferCHROMIUM
[3636:5016:0602/234252.518:ERROR:gpu_channel_manager.cc(200)] Exiting GPU process because some drivers cannot recover fr
om problems.
[3636:5016:0602/234252.521:ERROR:gl_context_egl.cc(209)] eglDestroyContext failed with error EGL_CONTEXT_LOST
[3636:5016:0602/234252.522:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteFramebuffersEXT without curren
t GL context
[3636:5016:0602/234252.524:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.526:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteVertexArraysOES without curren
t GL context
[3636:5016:0602/234252.528:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.530:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.532:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.533:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.535:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.537:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.539:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.541:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.543:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.545:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.548:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.551:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.553:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.556:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteTextures without current GL co
ntext
[3636:5016:0602/234252.558:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteProgram without current GL con
text
[3636:5016:0602/234252.560:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteProgram without current GL con
text
[3636:5016:0602/234252.562:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteProgram without current GL con
text
[3636:5016:0602/234252.564:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteProgram without current GL con
text
[3636:5016:0602/234252.566:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteProgram without current GL con
text
[3636:5016:0602/234252.569:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteProgram without current GL con
text
[3636:5016:0602/234252.571:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteProgram without current GL con
text
[3636:5016:0602/234252.573:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteProgram without current GL con
text
[3636:5016:0602/234252.575:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.577:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.580:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.582:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.584:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.586:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.588:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.589:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.591:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.593:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.594:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.596:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.598:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.599:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.601:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.603:ERROR:gl_bindings_autogen_gl.cc(12009)] Trying to call glDeleteShader without current GL cont
ext
[3636:5016:0602/234252.604:ERROR:gl_surface_egl.cc(1055)] eglDestroySurface failed with error EGL_CONTEXT_LOST
[3636:5016:0602/234252.606:ERROR:gl_context_egl.cc(209)] eglDestroyContext failed with error EGL_CONTEXT_LOST
[3636:5016:0602/234252.608:ERROR:gl_context_egl.cc(209)] eglDestroyContext failed with error EGL_CONTEXT_LOST
[3636:5016:0602/234252.608:ERROR:gl_context_egl.cc(209)] eglDestroyContext failed with error EGL_CONTEXT_LOST
INFO [2018-06-02 23:42:55] [moj.gram]  Session ended - 2018-06-02 23:42:55
INFO [2018-06-02 23:42:55] [moj.gram]  --------------------


Traceback (most recent call last):
  File ".\quickstart.py", line 25, in <module>
    session.login()
  File "H:\InstaBot\instapy\instapy.py", line 322, in login
    self.bypass_suspicious_attempt):
  File "H:\InstaBot\instapy\login_util.py", line 136, in login_user
    "//select[@class='_fsoey']/option[text()='English']").click()
  File "C:\Users\vortex\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.
py", line 385, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\vortex\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.
py", line 955, in find_element
    'value': value})['value']
  File "C:\Users\vortex\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\webdriver.
py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Users\vortex\AppData\Local\Programs\Python\Python36-32\lib\site-packages\selenium\webdriver\remote\errorhandl
er.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath"
,"selector":"//select[@class='_fsoey']/option[text()='English']"}
  (Session info: chrome=66.0.3359.181)
  (Driver info: chromedriver=2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91),platform=Windows NT 10.0.10586 x86_6
4)

**Comment by uluQulu** [comment]
Hi @arsayu 
That is a separate issue, check out #2133 and see if it works, if not, let me know :)

**Comment by arsayu** [comment]
Great.
Working like a charm 👍

**Comment by adaljack** [comment]
maybe the problem is that the element is into a other html into other html, i mean to iframe, the solution is right here https://www.youtube.com/watch?v=NhRx99uFUNk regards from mexico

**Comment by adaljack** [comment]
maybe the problem is that the element is into a other html into other html, i mean to iframe, the solution is right here https://www.youtube.com/watch?v=NhRx99uFUNk regards from mexico
