### ISSUE TITLE
follow user followers error when user name is not existing

### ISSUE THREAD

**Issue by tianxu0836** [InstaPy/InstaPy#2204]
## Expected Behavior
Skip non-existing user and log it.
## Current Behavior
Fail and stop running
## InstaPy Log
**INFO [2018-06-08 04:45:40] [my_user_name]  User 'ivanyuku_ph' [1/4]
ERROR [2018-06-08 04:46:06] [my_user_name]  Could not determine if ivanyuku_ph has followers
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\InstaPy\quickstart.py", line 33, in <module>
    session.follow_user_followers(['ivanyuku_ph'], amount=120, randomize=False, interact=True, sleep_delay=80)
  File "C:\Users\Administrator\Documents\GitHub\InstaPy\instapy\instapy.py", line 1925, in follow_user_followers
    self.logfolder)
ValueError: not enough values to unpack (expected 2, got 0)**

**Comment by uluQulu** [comment]
Hi @tianxu0836 
That bug was fixed while back, get updated files to solve it.

**Comment by spikeyhair** [comment]
Seems like the bug still exist when the given user doesn't exist.

This is the code I use:
session.interact_user_followers(username, amount=1, randomize=True)

Error:
Traceback (most recent call last):
  File "D:\Dropbox\Instapy\instapy\unfollow_util.py", line 811, in get_given_use
r_followers
    allfollowers = format_number(browser.find_element_by_xpath("//a[contains"
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\webdriver.py", line 385, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\webdriver.py", line 955, in find_element
    'value': value})['value']
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Una
ble to locate element: {"method":"xpath","selector":"//a[contains(@href,'followe
rs')]/span"}
  (Session info: chrome=67.0.3396.87)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5
ab),platform=Windows NT 6.1.7601 SP1 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Dropbox\Instapy\instapy\unfollow_util.py", line 816, in get_given_use
r_followers
    "return window._sharedData.entry_data."
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot re
ad property '0' of undefined
  (Session info: chrome=67.0.3396.87)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5
ab),platform=Windows NT 6.1.7601 SP1 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Dropbox\Instapy\instapy\unfollow_util.py", line 822, in get_given_use
r_followers
    "return window._sharedData.entry_data."
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\webdriver.py", line 627, in execute_script
    'args': converted_args})['value']
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files (x86)\Python\lib\site-packages\selenium\webdriver\remot
e\errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Cannot re
ad property '0' of undefined
  (Session info: chrome=67.0.3396.87)
  (Driver info: chromedriver=2.40.565498 (ea082db3280dd6843ebfb08a625e3eb905c4f5
ab),platform=Windows NT 6.1.7601 SP1 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "quickstart_verify.py", line 68, in <module>
    session.interact_user_followers(follow_username[0], amount=1, randomize=True
)
  File "D:\Dropbox\Instapy\instapy\instapy.py", line 1781, in interact_user_foll
owers
    self.logfolder)
  File "D:\Dropbox\Instapy\instapy\unfollow_util.py", line 827, in get_given_use
r_followers
    "//span[contains(@class,'g47SY')]")[1].text)
IndexError: list index out of range
