### ISSUE TITLE
Liking user's followers doesnt work; "Please enable following or liking in settings..."

### ISSUE THREAD

**Issue by Brainydaps** [InstaPy/InstaPy#2487]
## InstaPy configuration

from instapy import InstaPy

session = InstaPy(username='*******', password='*******')

session.login()
session.interact_user_followers(['curvygirls9ja'], amount=100, randomize=True)
session.set_do_like(enabled=True, percentage=80)
session.set_user_interact(amount=5, randomize=True, percentage=50, media='Photo')
session.set_do_follow(enabled=True, percentage=0)
session.set_comments(["great", "super", "good", "very good", "good", "wow",
                   "WOW", "cool", "GREAT","magnificent", "magical",
                   "very cool", "stylish", "beautiful", "so beautiful",
                   "so stylish", "so professional", "lovely",
                   "so lovely", "very lovely", "interesting", "Hmmm", 
                    "adorable", "excellent", "amazing"])
session.set_do_comment(enabled=True, percentage=20)

session.set_dont_like([])

session.end()

This is what is in the quickstart.py that keeps telling me to enable following or liking in settings in order to do interaction. Please how do i solve this? It just closes after telling me that.

**Comment by marcomokastyle** [comment]
@dr-dee move session.interact_user_followers at the end, before session.end(), this should solve the issue.

**Comment by MCCP96** [comment]
> @dr-dee move session.interact_user_followers at the end, before session.end(), this should solve the issue.

I tried this and I'm still having the issue
_______________________________________________________________________________________________________
CURRENT CODE:
from instapy import InstaPy
session = InstaPy(username='', password='')
session.login()

#Interact with user's followers
session.set_user_interact(amount=5, percentage=50, media='Photo')
session.set_do_follow(enabled=False, percentage=70)
session.set_do_like(enabled=False, percentage=70)
session.set_comments(["Cool", "Super!"])
session.set_do_comment(enabled=True, percentage=80)
session.interact_user_followers(['natgeo'], amount=10)

session.end()
_______________________________________________________________________________________________________

CURRENT OUTPUT:
..................................................................
INFO [2018-10-27 15:28:40] [qtsdaily.exe]  Logged in successfully!
''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
INFO [2018-10-27 15:28:44] [qtsdaily.exe]  Please enable following or liking in settings in order to do interactions.
INFO [2018-10-27 15:28:47] [qtsdaily.exe]  Sessional Live Report:
        |> LIKED 0 images  |  ALREADY LIKED: 0
        |> COMMENTED on 0 images
        |> FOLLOWED 0 users  |  ALREADY FOLLOWED: 0
        |> UNFOLLOWED 0 users
        |> INAPPROPRIATE images: 0
        |> NOT VALID users: 0
currently FOLLOWING X users & has got X FOLLOWERS

INFO [2018-10-27 15:28:47] [qtsdaily.exe]  Session ended!
________________________________________________________________________________________________________

Any help would be great! 
Thank you!

**Comment by yang0262** [comment]
Hi, I'm having the same problem. Any solutions?

**Comment by moyoleuki** [comment]
> Hi, I'm having the same problem. Any solutions?

Hiiii. 
Could you solve it?

**Comment by yang0262** [comment]
> > Hi, I'm having the same problem. Any solutions?
> 
> Hiiii.
> Could you solve it?

No I can't. It seems unable to get the list of either followers nor followings.

**Comment by axelmukwena** [comment]
Enable set_do_like as below,

`session.set_do_like(enabled=True, percentage=70)`
