### ISSUE TITLE
Failed to get followers count of

### ISSUE THREAD

**Issue by dpashutskii** [InstaPy/InstaPy#2639]
## Expected Behavior
Unfollow users which don't follow back

## Current Behavior
Can't get the list and get the error
```
INFO [2018-08-06 13:25:40] [<my_email>]  Failed to get followers count of '<my_email>'  ~empty list
        max_following=None,
INFO [2018-08-06 13:26:31] [<my_email>]  Failed to get following count of '<my_email>'  ~empty list
WARNING [2018-08-06 13:26:31] [<my_email>]  Unable to find the count of users followed  ~leaving unfollow feature
INFO [2018-08-06 13:26:31] [<my_email>]  --> Total people unfollowed : 0
```

## InstaPy configuration
I use config from the README:
```
session.unfollow_users(
        amount=500,
        InstapyFollowed=(True, "nonfollowers"),
        style="FIFO",
        unfollow_after=24*60*60,
        sleep_delay=501
    )
```

**Comment by tifDev** [comment]
Same

**Comment by waseem-brinsi** [comment]
the same problem @timgrossmann we need  your help

**Comment by tifDev** [comment]
I've solved this by adding set_do_like and set_dont_unfollow_active_users, try this:

```
session.set_do_like(your stuff)
session.set_dont_unfollow_active_users(your stuff)
session.unfollow_users(your stuff)
```
 @wassim1995

**Comment by dpashutskii** [comment]
Hey @tifDev. Can't try it because `set_dont_unfollow_active_users()` not working as well. See my issue https://github.com/timgrossmann/InstaPy/issues/2602.
Tried to add `set_do_like` - doesn't help. Still, have the same error:
```
Failed to get followers count of '<email>'  ~empty list
```

**Comment by leandersonandre** [comment]
Hi @guar47,
dont use email in your configs.
Put your username.

**Comment by waseem-brinsi** [comment]
thank you @leandersonandre it is work ......the problem is solved

**Comment by dpashutskii** [comment]
@leandersonandre OMG, it really solved. Thank you very much!

**Comment by davidkessler-ch** [comment]
Issue persists for me!! using username to log in..
It also fails to get the following count; (replaced username with me)
"...
INFO [2018-09-13 03:40:55] [me]  Starting to unfollow users..
INFO [2018-09-13 03:41:49] [me]  Failed to get followers count of 'me'  ~empty list
INFO [2018-09-13 03:42:40] [me]  Failed to get following count of 'me'  ~empty list
WARNING [2018-09-13 03:42:40] [me]  Unable to find the count of users followed  ~leaving unfollow feature
..."

And then in the "Sessional Live Report":
"...
currently FOLLOWING None users & has got None FOLLOWERS
...

Information in the logs:
followed.py >> empty
followingNum.txt >> First was working fine, then the count hit 0 and stayed there even though the number should have gone up again

**Comment by XavierRaul** [comment]
Hello. It's been two days since I have this problem. can someone help me ?

INFO [2018-12-14 12:53:43] [xavierledo_coach]  Starting to follow likers..
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

Getting likers from user:  marinlle

shuffling links
Got  24 , returning  6  links:  ['https://www.instagram.com/p/BrUfzqyFHH5/', 'https://www.instagram.com/p/BrIgCxjFgK-/', 'https://www.instagram.com/p/BqjiY5hlTV_/', 'https://www.instagram.com/p/BqnR7ABF0q3/', 'https://www.instagram.com/p/Bqu2ZNiF9L1/', 'https://www.instagram.com/p/Bq9YHAzlCLe/']
Few likes, not guaranteed you don't follow these likers already.
Got photo likers:  ['cyrilcoach', '17,208 others']

INFO [2018-12-14 12:55:00] [xavierledo_coach]  Failed to get followers count of 'b'17,208 others''  ~empty list

**Comment by brahimdev** [comment]
Hi @leandersonandre thx alot i changed it to username and it works THX
