### ISSUE TITLE
InstaPy Not working Anymore

### ISSUE THREAD

**Issue by forgottensword** [InstaPy/InstaPy#2835]
`Traceback (most recent call last):
  File "E:\Temp\instabot\InstaPy-master\instapy\unfollow_util.py", line 100, in get_following_status
    "//*[contains(text(), 'Requested')]")
  File "C:\Users\RSR\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.p
y", line 368, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\RSR\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.p
y", line 858, in find_element
    'value': value})['value']
  File "C:\Users\RSR\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.p
y", line 311, in execute
    self.error_handler.check_response(response)
  File "C:\Users\RSR\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandle
r.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"x
path","selector":"//*[contains(text(), 'Requested')]"}
  (Session info: chrome=68.0.3440.106)
  (Driver info: chromedriver=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e),platform=Windows NT 6.3.9600 x8
6_64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Temp\instabot\InstaPy-master\quickstart.py", line 116, in <module>
    session.like_by_tags(['usa'], amount=204)
  File "E:\Temp\instabot\InstaPy-master\instapy\instapy.py", line 1340, in like_by_tags
    self.logfolder)
  File "E:\Temp\instabot\InstaPy-master\instapy\unfollow_util.py", line 535, in follow_user
    are_we_following, follow_button = get_following_status(browser, user_name, logger)
  File "E:\Temp\instabot\InstaPy-master\instapy\unfollow_util.py", line 108, in get_following_status
    raise Exception
Exception

It Shows the above error after sometime

**Comment by forgottensword** [comment]
Handling of one exception causes another one. What's that about?

**Comment by Wraitheye** [comment]
have you tried doing a git pull? It solved some of my issues a week ago

**Comment by forgottensword** [comment]
This is not a week before issue bro. It's only happening to since few hours. I've been using instapy for weeks without any problems 247 @Wraitheye

**Comment by shariqmoosa** [comment]
I am facing the exact same issue from today..

**Comment by forgottensword** [comment]
@shariqmoosa Maybe Instagram changed their layouts

**Comment by alxhoff** [comment]
having the same issue

**Comment by kukkakeppi** [comment]
I've encountered this issue a few times after latest pull.

**Comment by forgottensword** [comment]
@alxhoff @kukkakeppi  guys... for time being, do one thing . set the do follow to false and this will solve the issue temporarily.
Note:- but make sure to pause InstaPy every two hours for sometime to avoid ban.
and also reduce the amount of likes and comments to smaller value than usual. give me some feedback too.

**Comment by shariqmoosa** [comment]
@forgottensword I can confirm when I use without do_follow it works fine.

**Comment by forgottensword** [comment]
This problem is solved

**Comment by shariqmoosa** [comment]
how after a update? because I am still facing this issue on do_follow? even i got it yesterday.

**Comment by forgottensword** [comment]
Maybe Instagram is still doing some testing in your area

**Comment by shariqmoosa** [comment]
Did you updated to fix this? or its auto fixed?

**Comment by forgottensword** [comment]
Auto fixed

**Comment by shariqmoosa** [comment]
looking forward to get this fixed..
