### ISSUE TITLE
Message: unknown error: Cannot read property 'scrollIntoView' of undefined

### ISSUE THREAD

**Issue by gregmoille** [InstaPy/InstaPy#3165]
## Expected Behavior

Work without error while unfollowing account previously followed by instapy

## Current Behavior

I started to get this error today when I try to unfollow with instapy. After loading the followers and going to the first to unfollow, it throw the error: 

```
ERROR [2018-10-19 10:10:56] [*****]  Unfollow loop error:  Message: unknown error: Cannot read property 'scrollIntoView' of undefined
  (Session info: chrome=69.0.3497.100)
  (Driver info: chromedriver=2.41.578706 (5f725d1b4f0a4acbf5259df887244095596231db),platform=Mac OS X 10.14.0 x86_64)
```

## InstaPy configuration

```python
session.login()
session.unfollow_users(amount=10, 
                               InstapyFollowed=(True, "nonfollowers"),
                               style="FIFO",
                               unfollow_after= 42*60*60,
                               sleep_delay=600)
```

**Comment by Tachenz** [comment]
Have this one as well!

**Comment by GOliveira10** [comment]
same

**Comment by greggjaskiewicz** [comment]
same issue here

**Comment by nazariyv** [comment]
same

**Comment by GOliveira10** [comment]
Interestingly it does not seem to happen when I run with a headless browser, only when I have the window open. Or at least, it hasn't happened yet.

**Comment by gregmoille** [comment]
Seems like the fix in #3159 (which is actually the same error reported with he scrollIntoView error)do the trick and fixes the scroll issue (at least I don't have it anymore)

**Comment by Tachenz** [comment]
This is so weird @gregmoille - as I get the above error, ONLY if I apply the #3159 fix. If I don't - no error :)

**Comment by nazariyv** [comment]
@Tachenz yup, started getting this error after I applied that fix too.

**Comment by Tachenz** [comment]
@nazariyv Well, since then they have merged it to the latest version. Try a clean download. I THINK, it fixed it for me (did not run much of a script these days yet)

**Comment by Eshank** [comment]
Hi Guys it's still happening for me . Any help would be appreciated

**Comment by willkwolf** [comment]
This issue happend today

Activity: Starting to follow user `Followers'

unfollow_util.py", line 707, in scroll_to_bottom_of_followers_list
    "arguments[0].children[1].scrollIntoView()", element

**Comment by Eshank** [comment]
Yes it did at the same line

**Comment by myehrajat** [comment]
me the same
 Sorry, an error occurred: Message: unknown error: Cannot read property 'scrollIntoView' of undefined

**Comment by brenohq** [comment]
same here

**Comment by t-jayw** [comment]
have this

**Comment by tE3m** [comment]
@t-jayw this error has been fixed. Update your files.

**Comment by luiztim** [comment]
@TarekJ03 no, it´s not fixed... everyday, i pull the code from the master branch, install requirements, etc before running the bot and the issue still persists. I limited the robot to unfollow only (because it´s less complex job) and to not load images. I used to run headless, but turned off this feature to analyze the behavior. The robot can successfully log me in, load my profile and, after loading the people I´m following, the issue happens and hungs the robot.
fyi - @gregmoille @timgrossmann

**Comment by tE3m** [comment]
@luiztim I'm sorry, but it is. Could it be possible that you installed InstaPy twice (`git` and `pip`)?

**Comment by luiztim** [comment]
Hi @TarekJ03 indeed, you are right 👍 the issue is solved :)

**Comment by Joyen12** [comment]
Hi @TarekJ03 and @luiztim, I have the same issue maybe it is possible I installed by git and pip because I got so many problem with the chromedriver that I tried everything for several days and it finally worked.
But I'm kind of a newbie and I don't know how to check if I have two version one by pip and one by git.
Could you tell me how to check and so how to remove the one by pip that is causing the problem I guess.
Thanks a lot

**Comment by Joyen12** [comment]
I can see I have two InstaPy folder but one with all the files and another one with just : assets  db  logs
I don't know why...

**Comment by Joyen12** [comment]
So it seems I have only one version installed because the other one just some file left inside.
But then how to know if it's installed by git or pip ?
When I do a git pull I get this :
remote: Enumerating objects: 22, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 23 (delta 12), reused 13 (delta 11), pack-reused 1
Dépaquetage des objets: 100% (23/23), fait.
Depuis https://github.com/timgrossmann/InstaPy
   06728ab..9a825e6  delay-unfollow-followbackers -> origin/delay-unfollow-followbackers
   ee73cc7..11f559e  dev        -> origin/dev
   582519e..eba6983  documentation/readme_update -> origin/documentation/readme_update
Déjà à jour.


But still getting this Error...:(
