### ISSUE TITLE
Element is not attached to the page document

### ISSUE THREAD

**Issue by andreescocard** [InstaPy/InstaPy#3857]
## Expected Behavior
Follow commenters

## Current Behavior
Started scapping links and shows an error

Traceback (most recent call last):
  File "script.py", line 36, in <module>
    session.follow_commenters(['XXXXX', 'XXXXXXX'], amount=50, daysold=365, max_pic = 100, sleep_delay=600, interact=False)
  File "/home/pi/InstaPy/instapy/instapy.py", line 715, in follow_commenters
    max_pic)
  File "/home/pi/InstaPy/instapy/commenters_util.py", line 241, in extract_information
    user_commented_list, pic_date_time = extract_post_info(browser)
  File "/home/pi/InstaPy/instapy/commenters_util.py", line 54, in extract_post_info
    while (" comments" in comments[1].text):
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.37 (undefined),platform=Linux 4.14.79-v7+ armv7l)

## Possible Solution (optional)
i think xpath needs update

## InstaPy configuration

session.login()
session.set_relationship_bounds(enabled=False)
session.set_skip_users(skip_private=False)
session.follow_likers(['XXXXX' , 'XXXXX'], photos_grab_amount = 2, follow_likers_per_photo = 3, randomize=True, sleep_delay=600, interact=False)
session.follow_commenters(['XXXXX', 'XXXXXX'], amount=50, daysold=365, max_pic = 100, sleep_delay=600, interact=False)
session.end()

**Comment by andreescocard** [comment]
Fixed #2261

**Comment by andreescocard** [comment]
https://github.com/timgrossmann/InstaPy/issues/3902

**Comment by ishandutta2007** [comment]
@andreescocard @timgrossmann I am still facing this in version 0.3.4
I recently started using follow_commenters , so I don't know since when it is there, @andreescocard please reopen the issue.
I am pasting my stacktrace:

> 
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/instapy/instapy.py", line 777, in follow_commenters
>     max_pic)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/instapy/commenters_util.py", line 241, in extract_information
>     user_commented_list, pic_date_time = extract_post_info(browser)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/instapy/commenters_util.py", line 61, in extract_post_info
>     comments = comment_list.find_elements_by_tag_name('li')
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 320, in find_elements_by_tag_name
>     return self.find_elements(by=By.TAG_NAME, value=name)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 685, in find_elements
>     {"using": by, "value": value})['value']
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
>     return self._parent.execute(command, params)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
>   (Session info: headless chrome=72.0.3626.121)
>   (Driver info: chromedriver=2.44.609545 (c2f88692e98ce7233d2df7c724465ecacfe74df5),platform=Mac OS X 10.13.6 x86_64)
> 
>
