### ISSUE TITLE
Instapy-chromedriver not supporting latest Chrome browser version

### ISSUE THREAD

**Issue by etemesi254** [InstaPy/InstaPy#4043]
The Instapy-chrome driver only supports Chrome upto versions  71 and since the update, the whole program quits with the error of ensure chromedriver is installed at .../insta-py/chromedriver_linux64..

**Comment by tE3m** [comment]
@breuerfelix is there a new binary you haven't included yet?

**Comment by timgrossmann** [comment]
Good catch 👍 
Sorry, my fault, we fixed it to 2.44 in the beginning since there was some trouble with 2.45.

Could you give: https://github.com/timgrossmann/InstaPy/pull/4046 a try?

**Comment by ryanoaks** [comment]
I cloned the repository, ran `pip install -U instapy` and am still seeing error `instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/user/.local/lib.python3.6/site-packages/instapy_chromedriver?chromedriver_linux64`

**Comment by tE3m** [comment]
Why would you clone the repository? It's not like that's the recommended installation...

**Comment by ryanoaks** [comment]
@TarekJ03 No, but its the easiest way to get the generic `quickstart.py` and other templates.

**Comment by ryanoaks** [comment]
Updated version of Chromium and had no problems.
