### ISSUE TITLE
Error: ImportError: cannot import name 'smart_run'

### ISSUE THREAD

**Issue by DomiPomidasd** [InstaPy/InstaPy#4289]
Just installed via Windows-Quickstart and receive following error message:

starting instapy with quickstart
================================
Traceback (most recent call last):
  File "../quickstart.py", line 3, in <module>
    from instapy import smart_run
ImportError: cannot import name 'smart_run' from 'instapy' (C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\instagram_py-0.0.1-py3.7.egg\instapy\__init__.py)
Press any key to continue . . .

cannot update with following message: 
An error occured. please try again. If the error persists please contact a developer.
Press any key to continue . . .

Installation was successful without any errors

**Comment by ishandutta2007** [comment]
Can you show your full template, if you are new to programming would suggest using a quickstart [template](https://github.com/InstaPy/instapy-quickstart/tree/master/quickstart_templates).

**Comment by DomiPomidasd** [comment]
fixed it: Python update und reinstall Instapy

**Comment by JennaDoll** [comment]
Hi guys im still getting the error below: i've installed and reintalled instapy over again and I am still getting this error when I click the mac_startcommand file to run instapy. below is my exact error:

Last login: Sun Aug  4 23:58:45 on ttys001
cs-iMac:~ cc$ /Users/cc/Documents/instapy-quickstart-master/run/mac_start.command ; exit;
Starting InstaPy with quickstart
====================
Traceback (most recent call last):
  File "../quickstart.py", line 3, in <module>
    from instapy import smart_run
ImportError: cannot import name smart_run
logout
Saving session...
...copying shared history...cp: /Users/cc/.bash_history: Permission denied

...saving history...-bash: /Users/cc/.bash_history: Permission denied
truncating history files...
...completed.

[Process completed]

**Comment by JennaDoll** [comment]
I have reinstalled instapy using the quick install file and this is the results I got, which is a successful install, so im not sure whats wrong. maybe someone can look into the result file pasted below and uncover something is off, Thanks in advance.

> `Last login: Mon Aug  5 00:09:30 on ttys002
cs-iMac:~ cc$ /Users/cc/Documents/instapy-quickstart-master/installation/MacOs/install.command ; exit;
/Users/cc/Documents/instapy-quickstart-master/installation/MacOs/install.command: line 3: [: !=: unary operator expected
Python is installed
====================
Pip is installed
====================
Chrome is installed
====================
Installing InstaPy...
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: instapy in /Library/Python/2.7/site-packages (0.5.8)
Requirement already satisfied: certifi>=2018.10.15 in /Library/Python/2.7/site-packages (from instapy) (2019.6.16)
Requirement already satisfied: selenium>=3.141.0 in /Library/Python/2.7/site-packages (from instapy) (3.141.0)
Requirement already satisfied: MeaningCloud-python>=1.1.1 in /Library/Python/2.7/site-packages (from instapy) (1.1.1)
Requirement already satisfied: urllib3>=1.24.1 in /Library/Python/2.7/site-packages (from instapy) (1.25.3)
Requirement already satisfied: protobuf>=3.6.1 in /Library/Python/2.7/site-packages (from instapy) (3.9.0)
Requirement already satisfied: plyer>=1.3.1 in /Library/Python/2.7/site-packages (from instapy) (1.4.0)
Requirement already satisfied: six>=1.11.0 in /Library/Python/2.7/site-packages (from instapy) (1.12.0)
Requirement already satisfied: regex>=2018.11.22 in /Library/Python/2.7/site-packages (from instapy) (2019.6.8)
Requirement already satisfied: EasyProcess>=0.2.3 in ./Library/Python/2.7/lib/python/site-packages/EasyProcess-0.2.3-py2.7.egg (from instapy) (0.2.3)
Requirement already satisfied: jsonschema>=2.6.0 in /Library/Python/2.7/site-packages (from instapy) (3.0.2)
Requirement already satisfied: instapy-chromedriver in /Library/Python/2.7/site-packages (from instapy) (2.46)
Requirement already satisfied: chardet>=3.0.4 in /Library/Python/2.7/site-packages (from instapy) (3.0.4)
Requirement already satisfied: configparser>=3.5.0 in /Library/Python/2.7/site-packages (from instapy) (3.7.4)
Requirement already satisfied: PyYAML>=3.13 in /Library/Python/2.7/site-packages (from instapy) (5.1.2)
Requirement already satisfied: grpcio>=1.16.1 in /Library/Python/2.7/site-packages (from instapy) (1.22.0)
Requirement already satisfied: idna>=2.7 in /Library/Python/2.7/site-packages (from instapy) (2.8)
Requirement already satisfied: clarifai>=2.4.1 in /Library/Python/2.7/site-packages (from instapy) (2.6.2)
Requirement already satisfied: emoji>=0.5.1 in /Library/Python/2.7/site-packages (from instapy) (0.5.3)
Requirement already satisfied: future>=0.17.1 in /Library/Python/2.7/site-packages (from instapy) (0.17.1)
Requirement already satisfied: requests>=2.20.1 in /Library/Python/2.7/site-packages (from instapy) (2.22.0)
Requirement already satisfied: PyVirtualDisplay>=0.2.1; sys_platform != "win32" in ./Library/Python/2.7/lib/python/site-packages/PyVirtualDisplay-0.2.1-py2.7.egg (from instapy) (0.2.1)
Requirement already satisfied: fake-useragent in /Library/Python/2.7/site-packages (from instapy) (0.1.11)
Requirement already satisfied: setuptools in /Library/Python/2.7/site-packages/setuptools-33.1.1-py2.7.egg (from protobuf>=3.6.1->instapy) (33.1.1)
Requirement already satisfied: attrs>=17.4.0 in /Library/Python/2.7/site-packages (from jsonschema>=2.6.0->instapy) (19.1.0)
Requirement already satisfied: functools32; python_version < "3" in /Library/Python/2.7/site-packages (from jsonschema>=2.6.0->instapy) (3.2.3.post2)
Requirement already satisfied: pyrsistent>=0.14.0 in /Library/Python/2.7/site-packages (from jsonschema>=2.6.0->instapy) (0.15.4)
Requirement already satisfied: futures>=2.2.0; python_version < "3.2" in /Library/Python/2.7/site-packages (from grpcio>=1.16.1->instapy) (3.3.0)
Requirement already satisfied: enum34>=1.0.4; python_version < "3.4" in /Library/Python/2.7/site-packages (from grpcio>=1.16.1->instapy) (1.1.6)
Requirement already satisfied: googleapis-common-protos<2,>=1.5.0 in /Library/Python/2.7/site-packages (from clarifai>=2.4.1->instapy) (1.6.0)
Requirement already satisfied: typing>=3.6 in /Library/Python/2.7/site-packages (from clarifai>=2.4.1->instapy) (3.7.4)
====================
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Successfully installed InstaPy!
logout
Saving session...
...copying shared history...cp: /Users/cc/.bash_history: Permission denied

...saving history...-bash: /Users/cc/.bash_history: Permission denied
truncating history files...
...completed.

[Process completed]`

**Comment by JennaDoll** [comment]
I even tried to run the quickstart file manually and got the same error below:

> cs-iMac:documents cc$ cd instapy-quickstart-master
cs-iMac:instapy-quickstart-master cc$ ls
LICENSE			installation		quickstart_templates
README.md		quickstart.py		run
cs-iMac:instapy-quickstart-master cc$ sudo python quickstart.py
Password:
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    from instapy import smart_run
ImportError: cannot import name smart_run
cs-iMac:instapy-quickstart-master cc$ 

> 

>
