### ISSUE TITLE
Raspberry Pi 3+ -> Error occured while deleting cookies

### ISSUE THREAD

**Issue by kranechan** [InstaPy/InstaPy#4441]
## Expected Behavior
To run the bot normally
## Current Behavior
Just 4 hours ago hit with the road bump of the following:
![image](https://user-images.githubusercontent.com/41986431/57838878-2356da00-77f8-11e9-8d63-e04c91150d18.png)

Error occur while deleting cookies

Tried:
-> Reinstall instapy
-> Reinstall chromedriver
-> Reboot
## InstaPy configuration
-> Running with raspberry pi 3+

**Comment by malimccalla** [comment]
I think its an issue with chromedriver 2.36 

```
python3 -m pip install --user instapy-chromedriver
```

That will upgrade you to latest version

**Comment by kranechan** [comment]
@malimccalla Not sure if I am confused. But as far as I know, raspberry Pi does not use the same instapy-chromedriver right?

Refer to: https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md

python3 -m pip uninstall instapy-chromedriver

I already executed:
python3 -m pip install --user instapy-chromedriver==2.36.post0
cp /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver assets/

But the error still occurring. What could be the problem?

**Comment by kranechan** [comment]
I tried the basic quickstart.py also facing this issue:

![image](https://user-images.githubusercontent.com/41986431/57843247-7e8cca80-7800-11e9-8076-8141b5c40c5f.png)

**Comment by kranechan** [comment]
will it caused by this:
![image](https://user-images.githubusercontent.com/41986431/57843355-b6940d80-7800-11e9-97a5-afa08608c087.png)

**Comment by malimccalla** [comment]
I had the same issue, it just suddenly stopped working. Once I upgrade instapy-chromedriver it worked fine. Try running the command I put above on your pi and see if it fixes your problem

**Comment by kranechan** [comment]
Hi @malimccalla are you using raspberry pi? 

I followed your instruction. Nope still same error. I changed my password as well but the session feedback was:

![image](https://user-images.githubusercontent.com/41986431/57844321-628a2880-7802-11e9-904e-b20c89d29399.png)

**Comment by malimccalla** [comment]
Yes I'm using raspberry pi. In your above screenshot it says your chromedriver version is still 2.36 - please run this instead

```
pip3 install instapy-chromedriver -U
```

**Comment by kranechan** [comment]
@malimccalla tried but still same:

![image](https://user-images.githubusercontent.com/41986431/57845198-16d87e80-7804-11e9-994e-5c1a0b5ea586.png)

Wonder what causes the page crash @uluQulu @timgrossmann any idea?

**Comment by malimccalla** [comment]
Your version is still 2.36 - I upgraded from that version to 2.46 and everything started working again. If you figure out how to upgrade your instapy-chromedriver version it will work.

**Comment by kranechan** [comment]
@malimccalla how do you get 2.46? Could you navigate to /home/pi/.local and get inside the python 3.5 and send the chromedriver here?

@uluqulu where could I get the latest chromedriver for the /asset folder in raspberry pi?

**Comment by kranechan** [comment]
Okay guys, it is not about the chrome version or anything like it. It is because of the file permission. All you need to do is:

`sudo chmod 777 \path\to\your\chromedriver`

where the \path could be pointing towards your assets (those who are using standalone). 

Side discovery: To update your chrome driver to the latest version
`sudo apt-get install chromium-driver`

copy the "chromedriver" from /usr/bin to your asset folder

**Comment by kranechan** [comment]
Okay guys, now the thing occurs intermittently where 90% crash and 10% okay >< @malimccalla yours was stable?

**Comment by xerZV** [comment]
Same error here - raspberry pi 3+

**Comment by kranechan** [comment]
After formatting raspberry pi and mix&match chromedriver for hours and result is still not expected,

Discovered a temporary bypass:

add to your session `use_firefox=True`

install firefox `sudo apt-get install firefox-esr`
In your raspberry pi download this: https://github.com/mozilla/geckodriver/releases/download/v0.17.0/geckodriver-v0.17.0-arm7hf.tar.gz
or shorter link: https://bit.ly/2HdfWu5

extract geckodriver from the above file to `/usr/bin`

Run your script.

PS: headless option is not working for firefox even `headless_browser=True` any idea @uluQulu  @timgrossmann @converge  ?

PS2: It will use more resources than usual as the headless browser option is not functioning

**Comment by converge** [comment]
@silensinator you can use nogui=True , maybe you will also need to set the window size in browser.py:
```python
if use_firefox:
 44         firefox_options = Firefox_Options()
 45
 46         if headless_browser:
 47             firefox_options.add_argument('-headless')
 48
 49         if browser_profile_path is not None:
 50             firefox_profile = webdriver.FirefoxProfile(
 51                 browser_profile_path)
 52         else:
 53             firefox_profile = webdriver.FirefoxProfile()
 54
 55         # set window size
 56         firefox_options.add_argument('--width=1920')
 57         firefox_options.add_argument('--height=1080')
```

**Comment by kranechan** [comment]
@converge appreciate your shift reply.

Not sure is it raspberry pi 3 issue. I tried:

1. adjusting the width/height in browser.py
2. incorporating `nogui=True`

But those actions (either/and) will crash/abrupt close of firefox when it tries to crawl the follower's list

For now I will just leave it as default:
```
(username=insta_username,
password=insta_password,
 use_firefox=True,
#nogui=True,
headless_browser=True,
disable_image_load=True)
```

**Comment by dontic** [comment]
@silensinator well after days of research I finally found what I think is the solution. All thanks to the great @JoeFertig 

For now I have 2 instances running and they haven't crashed yet. I'll keep updating.

**New updated Raspberry Pi 3b & 3b+ guide** [HERE](https://github.com/InstaPy/instapy-docs/pull/4/commits/0d61f5f0c419a2dee3549a7c85182386cfb4613c#diff-a61b7e12bc722b739036bb7b82f31437)

If you had a previous version of InstaPy with 2.36 chromedriver you just need to do the following:

Uninstall chromedriver 2.36: 

1. `python3 -m pip uninstall instapy-chromedriver`
2. Delete chromedriver from /InstaPy/assets folder

Install new chromedriver 3.0.0 beta version:

3. `cd InstaPy`
4. `cd assets`
5. `wget https://github.com/electron/electron/releases/download/v3.0.0-beta.5/chromedriver-v3.0.0-beta.5-linux-armv7l.zip`
6. `unzip chromedriver-v3.0.0-beta.5-linux-armv7l.zip`
7. `chmod 755 chromedriver`
8. `chmod +x chromedriver`
9. `rm chromedriver-v3.0.0-beta.5-linux-armv7l.zip`

**Comment by Joker6888** [comment]
Tried it out because I have the same problem, no solution here. Once my unfollow-action ran good, then the next day same problem again.

**Comment by jeremycjang** [comment]
Followed @dontic 's steps , testing

**Comment by dontic** [comment]
> Followed @dontic 's steps , testing

Update on my side.
One of my two instances crashed with :

> Error occurred while deleting cookies from web browser!
	b'Message: unknown error: session deleted because of page crash\nfrom tab crashed\n  (Session info: headless chrome=72.0.3626.121)\n  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)

After running it again it has been running fine until now.

Don´t know why it still says:

> chromedriver=2.36 

Will keep testing.

**Comment by jeremycjang** [comment]
@dontic Also crashed for me today after a few successful instances run consecutively. 

Not sure if this might be related/what the design decision was surrounding going with version 2.36:

https://bugs.chromium.org/p/chromedriver/issues/detail?id=2333

**Comment by JoeFertig** [comment]
> @silensinator well after days of research I finally found what I think is the solution. All thanks to the great @JoeFertig

Hello & thanks!
Well the main problem is that you need a certain chromedriver for a certain chromium-browser. Most people update the chromedriver to a version that is not matching with the chromium-browser.

In our case ("unkown SessionID" & "error while deleting cookies" etc) I did some tests cause I still experience this problem. So the best workaround atm is to remove chromium-browser and re-install it. You can also try and delete all the browser data manually from the chromium-browser. 

I think the main problem is Rasps amrV7 chip and the lack of developement for that chipset. My solution is to move from a Pi to another micro computer which has no arm chips implemented.

**Comment by Joker6888** [comment]
Thank you for your information. Is there a page where I can see which version of Chromium and Chromedriver matches together so I can install both fitting versions of it? The problem on the raspberry pi is killing me right now. Which micro computer do you recommend for the Instapy project?

**Comment by dontic** [comment]
@JoeFertig thanks again! If it comes to that I will definitely check out some other microcomputers.

For now I'm testing another possible solution, can't say if it works yet, will update in a day or so.

Im going to put it here if anyone wants to test it (@jeremycjang @silensinator @Joker6888):

1. Uninstall chromium 72: 
`sudo apt-get purge chromium-browser`
`rm -rf ~/.config/chromium`

2. Install  chromium 65 (because of https://github.com/timgrossmann/InstaPy/issues/4033#issuecomment-466074266):
`wget http://launchpadlibrarian.net/361669485/chromium-browser_65.0.3325.181-0ubuntu0.14.04.1_armhf.deb; sudo dpkg -i chromium-browser_65.0.3325.181-0ubuntu0.14.04.1_armhf.deb`

3. Install codecs:
`wget http://launchpadlibrarian.net/361689926/chromium-codecs-ffmpeg_65.0.3325.181-0ubuntu0.16.04.1_armhf.deb; sudo dpkg -i chromium-codecs-ffmpeg_65.0.3325.181-0ubuntu0.16.04.1_armhf.deb`

4. Use this with chromedriver 2.36 (install it like in the RPi tutorial)

Hope this is the right match between chromium and chromedriver. It's been working fine now but I'd like to give it some time.

**Comment by jeremycjang** [comment]
@dontic I'm currently testing with chromium 65 and instapy-chromedriver 2.36.post0 . 

If a chromedriver is present in the assets folder, it'll use that chromedriver instead of the instapy-chromedriver that was built for the pi, so I deleted the previous chromedriver to get the program to use ```instapy-chromedriver``` . 

It's working well so far, but will continue testing as well. Looks like for whatever reason, I already had the 3.0.0 beta version stored in the assets folder of the workspaces the program was pulling from!

**Comment by JoeFertig** [comment]
Here is a compatibility list of chromedrivers and chrome(*ium) browsers:

http://chromedriver.chromium.org/downloads

However, my solution is more a workaround than a real fix.

**Comment by Joker6888** [comment]
@dontic seems to work, had to install matching codec but now it’s running again with chromium 65 and 2.36/0.
Will keep testing it.

**Comment by dontic** [comment]
@Joker6888 I also installed the codecs, forgot to say that, edited in my previous post.

**Comment by Joker6888** [comment]
Crashed after 16 minutes with unknown session ID. Any ideas?

**Comment by JoeFertig** [comment]
> Crashed after 16 minutes with unknown session ID. Any ideas?

did you remove and re install chromium-browser?

**Comment by dontic** [comment]
@Joker6888 yup mine just crashed too. The only difference I can see is that now it doesn't crash because of the cookies problem:

<details>
<summary>
<b>Error message</b>
</summary>

> OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
> 
> INFO [2019-05-21 17:14:58] []  Session ended!
> oooooooooooooooooooooooooooooooooooooooooooooooooooooo
> 
> 
> 
> Traceback (most recent call last):
>   File ".py", line 113, in <module>
>     session.like_by_tags(random.sample(like_tag_list, 3),amount=random.randint(15, 50), interact=True) 
>   File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 1877, in like_by_tags
    self.user_interact_media)
>   File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 1967, in like_by_users
    media)
>   File "/home/pi/.local/lib/python3.5/site-packages/instapy/like_util.py", line 408, in get_links_for_username
>     if not is_page_available(browser, logger):
>   File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1658, in is_page_available
    page_title = get_page_title(browser, logger)
>   File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1720, in get_page_title
    explicit_wait(browser, "PFL", [], logger, 10)
>   File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1547, in explicit_wait
    result = wait.until(condition)
>   File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 71, in until
>     value = method(self._driver)
>   File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1535, in <lambda>
    "return document.readyState")
>   File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script
>     'args': converted_args})['value']
>   File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: unknown sessionId
>   (Session info: headless chrome=65.0.3325.181)
>   (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)
</details>

Right now I'm looking at [alternatives](https://www.electromaker.io/blog/article/best-raspberry-pi-alternatives-2019) to replace the Raspberry

**Comment by Joker6888** [comment]
@joeFertig yes i did, removed everything and reinstalled. Error log shows the right version (65 & 2.36)

**Comment by JoeFertig** [comment]
That's pretty bad.
I really don't get why we get this error more and more.
I tried firefox but somehow it's not able to log in. Looks like it stops typing the complete password when trying.

**Comment by Joker6888** [comment]
Made a few testings, it seems to work with the 65 Chromium and beta 3 chromedriver. 2 runs just work fine, keep on testing.

**Comment by jeremycjang** [comment]
My Pi crashed and I had to do a completely fresh install following the latest How to Raspberry Pi guide:

https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md

The session now crashes after navigating to instagram.com with an error implying an empty response, though a response was returned successfully.

Switching to testing in FireFox for now to confirm if it's a good alternative while the crashing due to chromedriver gets sorted out

**Comment by jeremycjang** [comment]
@Joker6888 @dontic @JoeFertig the latest version of NOOBS came with Chromium 72, but it doesn't work running with `chromedriver 2.36.post0` nor the supposedly compatable `chromedriver 2.46` .

Can you share the linux command to install Chromium 65? `sudo apt-cache madison chromium-browser` only returns Chromium 72

thanks!

**Comment by JoeFertig** [comment]
Hey @jeremycjang does firefox work for you?
Is it stable?
I can't get it run.

**Comment by JoeFertig** [comment]
For everyone who has the 'unknown SessionID' or the 'error deleting cookies from browser' problem please try this:

sudo apt install chromium-browser chromium-codecs-ffmpeg

then run again and tell me if it fixed your problems.

**Comment by dontic** [comment]
Ok guys so after that initial crash it hasn't crashed since. It's been 2 days and it has been fine, no errors on my 2 instances.

@jeremycjang You can refer to my previous post https://github.com/timgrossmann/InstaPy/issues/4441#issuecomment-494371736 

I think, as @JoeFertig says, that is the codecs that do the trick.

Will keep updating with any errors. 

To summarise:
**For now Chromium 65 and chromedriver 2.36 post0 is the combination that's working for me.**

**Comment by jeremycjang** [comment]
I think the Raspberry Pi How to documentation should be updated with that. Not familiar with how to do that on GitHub or how to modify the code now that the whole program's through a single `pip install` , but happy to do so if I learn how!

**Comment by jeremycjang** [comment]
@JoeFertig FireFox-esr was working; I was never able to get normal FireFox to work on the RPi.

However, commenting from FireFox-esr leaves a �  at the end of every comment due to how the ARMS chip interacts with the encodings chosen for InstaPy. It's usable, but reading through https://github.com/timgrossmann/InstaPy/issues/1411 and https://github.com/timgrossmann/InstaPy/issues/1740 it sounds like you would have to tweak the core code to fix it, which would mess with how the commenting works when using Chromedriver

Essentially, you'd have to make a choice between which browser you primarily want to use for running the program and make the tweak for commenting depending on your choice. Personally, I only encountered the crash in this issue when using the like-based actions, so I'm running firefox-esr for like-only programs

Still testing to see if it can complete a `firefox-esr` `like_by_location` + `like_by_tags`  run without freezing or crashing, will provide an update!

**Comment by JoeFertig** [comment]
@dontic nice!
can you send me a link where I can get the chromium 65 version?

@jeremycjang all FF versions incl. the esr are crashing when I try to run them. Even when I run them manually by clicking the icon.

**Comment by jeremycjang** [comment]
@JoeFertig  @dontic provided the steps for Chromium 65 here: https://github.com/timgrossmann/InstaPy/issues/4441#issuecomment-494371736

For convenience, here it is again:

Uninstall chromium 72:
sudo apt-get purge chromium-browser
rm -rf ~/.config/chromium

Install chromium 65 (because of #4033 (comment)):
wget http://launchpadlibrarian.net/361669485/chromium-browser_65.0.3325.181-0ubuntu0.14.04.1_armhf.deb; sudo dpkg -i chromium-browser_65.0.3325.181-0ubuntu0.14.04.1_armhf.deb

Install codecs:
wget http://launchpadlibrarian.net/361689926/chromium-codecs-ffmpeg_65.0.3325.181-0ubuntu0.16.04.1_armhf.deb; sudo dpkg -i chromium-codecs-ffmpeg_65.0.3325.181-0ubuntu0.16.04.1_armhf.deb

Use this with chromedriver 2.36 (install it like in the RPi tutorial)

_unrelated to title issue, but inquired about in chain_

`Firefox-esr` almost completed the full run for me, then crashed with the following stack trace:

```
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 1726, in like_by_tags
    self.logger)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/like_util.py", line 236, in get_links_for_tag
    top_elements = browser.find_element_by_xpath('//main/article/div[1]')
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response

   raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette
```

However, I believe could be because I ran a pretty long session liking 1500 posts. I'm fairly confident the program will work well using shorter sessions and am about to test this!

**Comment by jeremycjang** [comment]
@JoeFertig  Firefox-esr crashed again with the same stack trace, appears to be a random occurrence

Here's to hoping the chromedriver fix resolves all these issues

**Comment by dontic** [comment]
It´s been 3 days now and none of my 2 instances of liking by tags bot have crashed using chromium 65 and chromedriver 2.36

Hopefully this means that the issue is solvable with this combination.

If I experience any issues I´ll write updates in this thread.

**Comment by JoeFertig** [comment]
So to close this issue:

sudo apt install chromium-browser chromium-codecs-ffmpeg

does the job. Anyone of you still experiencing problems?

**Comment by dontic** [comment]
> So to close this issue:
> 
> sudo apt install chromium-browser chromium-codecs-ffmpeg
> 
> does the job. Anyone of you still experiencing problems?

Mine crashed again once, I think this solves the issue partially, as it crashes with much less frequency, taking days to do so.

Hopefully somebody finds another way to permanently solve this.

**Comment by Joker6888** [comment]
Mine crashed again too, after one full day of running. Any ideas to solve the problem?

**Comment by Joker6888** [comment]
Does anyone have an idea what the difference between the normal codecs and the -extra codecs is? my raspberry is giving an unexpected problem with the codec because the do not match with chromium while in upgrade-mode. Can I ignore the chromium and codec package in apt-get?

**Comment by jeremycjang** [comment]
I haven't experienced any more crashes using Chromium with the suggested solution!

I was observing the crashes occur when running a single program with a lot of activities for a long period of time, specifically when using the liking functions (never saw a crash with the follow actions). So I broke my single program down into smaller programs to run consecutively using simple Linux chaining, haven't experienced any issues other than the Pi generally overheating/rebooting once

**Comment by jeremycjang** [comment]
New stack traced observed:
```
  logfolder)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/unfollow_util.py", line 192, in get_following_status
    following_status = follow_button.text
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=65.0.3325.181)
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.42-v7+ armv7l)
```
Unable to determine if this was caused by any updates to IG or other reasons quite yet

**Comment by dontic** [comment]
Mine continues to fail, much less than before, it takes more than one day to crash, but it eventually crashes. So no solution on my end...

**Comment by anitato** [comment]
After updating InstaPy, I also followed the directions from this thread by @JoeFertig @dontic @jeremycjang (thank you for all your help!)

Unfortunately, InstaPy still crashes eventually. I have different scripts for different actions set up on crontab, running headlessbrowser and/or nogui (both seem to work). Unfollowing never seems to crash, but liking/following/interacting crashes every time.

**Comment by kranechan** [comment]
@dontic solution works! Been trying for several weeks now and it so far does not give any issue anymore. Those who have trouble installing remember to use the parameter '-f' to force it through especially when chromium looking for the other dependencies

**Comment by jeremycjang** [comment]
@silensinator Can you clarify which command to use the `-f` flag on? I've still occassionally encountered the crashes

**Comment by Joker6888** [comment]
Can't proof that as well, my session is failing more and more. Some ran 3 hours, some only 2 minutes. Next Problem: the unknown session id failed while getting the users in full range to unfollow, so my script (which only should unfollow the ones that are not following back) unfollows to much people.

**Comment by anitato** [comment]
Mine also keeps crashing after less than an hour of running (if not shorter). The session only completed 30 likes total:

`Traceback (most recent call last):                                                                                            
  File "quickstart.py", line 56, in <module>                                                                      
    session.like_by_tags(random.sample(like_tags_list, random.randint(19,22)), amount=random.randint(41,51), interact=True, sk
ip_top_posts=True)                                                                                                            
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 1907, in like_by_tags                           
    self.user_interact_media)                                                                                                 
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 2000, in like_by_users                          
    media)                                                                                                                    
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/like_util.py", line 409, in get_links_for_username                
    if not is_page_available(browser, logger):                                                                                
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1654, in is_page_available                         
    page_title = get_page_title(browser, logger)                                                                              
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1716, in get_page_title                            
    explicit_wait(browser, "PFL", [], logger, 10)                                                                             
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1543, in explicit_wait                             
    result = wait.until(condition)                                                                                            
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/support/wait.py", line 71, in until                    
    value = method(self._driver)                                                                                              
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/util.py", line 1531, in <lambda>                                  
    "return document.readyState")                                                                                             
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 636, in execute_script      
    'args': converted_args})['value']                                                                                         
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute             
    self.error_handler.check_response(response)                                                                               
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response   
    raise exception_class(message, screen, stacktrace)                                                                        
selenium.common.exceptions.WebDriverException: Message: unknown error: unknown sessionId                                      
  (Session info: headless chrome=65.0.3325.181)                                                                               
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.19.42-v7+ armv7l)`

It practically renders InstaPy unusable for me. Is there no fix in sight?

**Comment by jeremycjang** [comment]
This might be an issue with the Chromedriver and not InstaPy itself.

I tried some Google fu and not sure how reliable this it, but supposedly the unknown session ID issue was resolved in ChromeDriver 2.38 (see the notes): https://www.cnblogs.com/BeyondTechnology/p/9523928.html 

Has anyone tried using that driver on the Pi before? According to that site, it's still supports Chromium 65

**Comment by Joker6888** [comment]
It should fix the problem but there is no 2.38 for Debian, the possible choices are 2.36.post0 or 2.44.

**Comment by thejeromelouis** [comment]
I have the same  problem with my RPi3B+. I'm using Version 2.36 chrome-driver and chromium 65. I don't have any problem while unfollowing but it always crashes by liking or following. I already tried the solutions described here but still the same error. Any solutions yet?

`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot determine loading status
from unknown error: unknown sessionId`

**Comment by gherkins** [comment]
i ended up using the chromedriver version <del>shipped with `chromium-browser`</del>
installed via `sudo apt-get install chromium-chromedriver ` (see comments below)

pi@raspberrypi:~ $ chromium-browser --version
Chromium 72.0.3626.121 Built on Raspbian , running on Raspbian 9.9
pi@raspberrypi:~ $ chromedriver --version
ChromeDriver 72.0.3626.121
pi@raspberrypi:~ $ which chromedriver
/usr/bin/chromedriver

`ln -s /usr/bin/chromedriver InstaPy/assets/chromedriver`


seems to work fine so far...

**Comment by thejeromelouis** [comment]
@gherkins How did you get the ChromeDriver 72 on your Pi? How can I install them? If I install Chromium 72, there are no drivers in my /usr/bin/ Folder.

**Comment by thejeromelouis** [comment]
Solved: This worked for me: `sudo apt-get install chromium-chromedriver`

**Comment by gherkins** [comment]
> Solved: This worked for me: `sudo apt-get install chromium-chromedriver`

ok, i thought it came as a dependency of `chromium-browser `

👍

**Comment by jeremycjang** [comment]
supposedly the chromedriver for Chromium 72 does not support ARMs chip devices like the RPi. Does this seem to not be the case/have you still had no unknown session ID crashes? @gherkins

**Comment by thejeromelouis** [comment]
Since one day now there arent any unknown session ID crashes on my RPi.

**Comment by gherkins** [comment]
> supposedly the chromedriver for Chromium 72 does not support ARMs chip devices like the RPi. Does this seem to not be the case/have you still had no unknown session ID crashes? @gherkins

hm, no 🤷‍♀ working pretty stable ever since....

**Comment by jeremycjang** [comment]
@joefertig do you see any potential conflict with running the program with Chromium 72 + latest chromedriver as noted by some above ^ ?

**Comment by jeremycjang** [comment]
Testing using the latest chromium and chromedriver on RPi as well.

**Comment by jeremycjang** [comment]
@gherkins Do you still have an `instapy-chromedriver` installed? Removing the `instapy-chromedriver 2.36,post0` module results in the following stack trace due to the `instapy_chromedriver` module getting removed but called in the `file_manager.py`:

```
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 309, in __init__
    self.set_selenium_local_session()
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 361, in set_selenium_local_session
    self.logger)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/browser.py", line 88, in set_selenium_local_session
    chromedriver_location = get_chromedriver_location()
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/file_manager.py", line 224, in get_chromedriver_location
    from instapy_chromedriver import binary_path
ImportError: No module named 'instapy_chromedriver'
```

With that appearing in different files in the code, I'm not sure how you can get the program to call Chromedriver 72 unless I messed up somewhere.

**Comment by gherkins** [comment]
yes, but not the 2.36,post0 version but the one being installed as a dependency of intapy by default (2.46 i think)

I symlinked the chromedriver 72 executable in my assets folder:
`ln -s /usr/bin/chromedriver InstaPy/assets/chromedriver `

that should make instapy use that version, i think...

**Comment by Frituurpanda** [comment]
@gherkins does this only work for chrome 72? The latest version still results in the same old stacktrace: 

`selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=74.0.3729.157 (7b16107ab85c5364cdcd0b2dea2539a1f2dc327a-refs/branch-heads/3729@{#998}),platform=Linux 4.19.50-v7+ armv7l)`

Thoughts?

**Comment by jeremycjang** [comment]
@gherkins can you confirm if you still haven’t experienced any crashes since your changes/the symlinking?

**Comment by gherkins** [comment]
@jeremycjang 
well, it did run smoothly for some couple of days.   
currently it doesnt work because of the error fixed in 5.5...   
but i guess chromedriver still works.

**Comment by pezzotto** [comment]
The @gherkins solution worked for me till now. Symlinked the latest chromedriver obtained by sudo apt-get install chromium-chromedriver and it’s going. Before I was totally unable to login.

I think the RPiB3+ is the most problematical architecture to run instapy but that’s why we use it right?

**Comment by Frituurpanda** [comment]
@gherkins Following those steps for the latest version still throws that error for me so you might have done more modifications i'm thinking?

**Comment by gherkins** [comment]
> @gherkins Following those steps for the latest version still throws that error for me so you might have done more modifications i'm thinking?

with what python version are you running your script?
i'm using python3.7, but thats the only thing i can think of...

**Comment by mwargan** [comment]
@gherkins I'm running into the same issue as @Frituurpanda on 3.7 and Raspian Buster :/.

However, this solution worked great! https://github.com/timgrossmann/InstaPy/issues/4441#issuecomment-494371736

**Comment by githubbbie** [comment]
Linked to issue #4166  and still NOT resolved.
