### ISSUE TITLE
Chromedriver chrashes when InstaPy started with `headless=False` and nogui=`True`

### ISSUE THREAD

**Issue by filo87** [InstaPy/InstaPy#4607]
## Expected Behavior
InstaPy should run with `headless_browser=False` and `nogui=True` so that the resulting Xfvb screen on :1001 can be monitored with a custom VNC connection

## Current Behavior
When starting InstaPy with `headless_browser=False` and `nogui=True` chromedriver crashes raising a WebDriver Exception.

## Possible Solution (optional)
chromedriver should always be started with option `--no-sandbox` to avoid crashes.

https://github.com/timgrossmann/InstaPy/blob/20061fcd6673c50749100df15d4e5f86085ef43c/instapy/browser.py#L88-L99

`chrome_options.add_argument('--no-sandbox')` on line 99 should be moved to right after `chrome_options.add_argument('--disable-setuid-sandbox')` to line 94.

### Error Logs
```
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Custom workspace set: "/opt/boxagram-box/libs/InstaPy" :]

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/opt/boxagram-box/libs/InstaPy"
ERROR    [2019-07-02 15:10:58] [0x281509d8a65] [******] Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.19.53-sunxi armv7l)
Traceback (most recent call last):
  File "/opt/boxagram-box/libs/InstaPy/instapy/browser.py", line 146, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=73.0.3683.75,platform=Linux 4.19.53-sunxi armv7l)
```

**Comment by filo87** [comment]
addressed in pull request https://github.com/timgrossmann/InstaPy/pull/4608

**Comment by alecrimi** [comment]
No,
I have 
chrome_options.add_argument('--no-sandbox') on line 99 should be moved to right after chrome_options.add_argument('--disable-setuid-sandbox') to line 94.
and still get the erro

**Comment by filo87** [comment]
can you post the exception log ? what chromedriver version are you running?
