### ISSUE TITLE
Login Error // IndexError: list index out of range

### ISSUE THREAD

**Issue by brandonkovacs** [InstaPy/InstaPy#463]
Everything was working fine - but then all of a sudden, I started getting this error. I'm currently using the master branch.

>  python bot.py 

Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    session.login()
  File "/home/centos/InstaPy/instapy/instapy.py", line 124, in login
    if not login_user(self.browser, self.username, self.password):
  File "/home/centos/InstaPy/instapy/login_util.py", line 24, in login_user
    action = ActionChains(browser).move_to_element(inputs[0]).click().send_keys(username) \
IndexError: list index out of range

**Comment by botpadawan** [comment]
Also encountered this error in all accounts just today

**Comment by alvintclam** [comment]
And all server got the same issue suddenly

**Comment by smallredcape** [comment]
I am also encountering this new login problem. Looks like Instagram changed something on the login page?

**Comment by balakedev** [comment]
Also not able to log in

**Comment by BernardoGO** [comment]
Fixed on PR #457. Instagram changed div positioning.

**Comment by brandonkovacs** [comment]
@BernardoGO - Are you sure? Just tried using that commit file and it still isn't working.... I believe IG made a change to their login page a few hours ago. That commit is a day old?

**Comment by BernardoGO** [comment]
The commit isn't a day old. My virtual machine messed the commit datetime.
Yes, I'm sure it fixes the problem. The mechanism to find the text boxes was rewritten and is now working.

**Comment by mihikadutta** [comment]
@BernardoGO why have we doubled the sleep time in the login utils file? 
@brandonkovacs Could you try with this PR (https://github.com/timgrossmann/InstaPy/pull/465/files)
If anyone is looking out for a quick fix then it just requires a minor change in the login_util.py
`inputs = browser.find_elements_by_xpath("//form/div/input")`
to
`inputs = browser.find_elements_by_xpath("//form/div/div/input")`

Apparently there is some minor DOM update from Instagram side and hence the issue. I have verified it on local setup, so it should do fine.

**Comment by PastaGringo** [comment]
[This](https://github.com/timgrossmann/InstaPy/pull/465/commits/112b1796c51f4eb86c72f4536d5d323aa8c17522) commit fixed the issue! Thanks @meherranjan
