### ISSUE TITLE
Not able to Login to Instagram (Cookie File /Login A/B test detected! Trying another string...)

### ISSUE THREAD

**Issue by depayem** [InstaPy/InstaPy#4908]
Hello Everybody,
me and my team are following all developments on this thread on a daily basis and are really happy that so many people are contributing to InstaPy and fighting Instagram and their new Algorithm.

Currently we are stuck on a Login Problem. Something really strange is happening:

Today we updated to 0.6.1 this morning. We ran one account that was already running on 0.6.0 (Raspberry 4 with a proxy) and the login **worked flawless** and the programmed script as well.

We then set up a new Raspberry, different Proxy and a **different account**, which was **not** running on 0.6.0 and had **no cookie file** before.
The login is not working at all, cookie file is not being created and we are getting the same issues referenced in #4877 .

We already tried to fix it by adding the proposed solution from @Mr-HaleYa in the Thread by changing up what he mentioned without success:

> Line 159 "login_elem_no_such_exception": "//a[text()='Log``` In']",
> 
> It looks like this ^^^
> 
> It needs to look like this
> 
> Line 159 "login_elem_no_such_exception": "//button[text()='Log In']",

Same Login Problems. 
When we watch the script running the page refreshes one time and the Button "Log In" is still displayed, the script doesnt even manage to move  past the Log In Button to actually insert the Login Credentials. 
We also tried to manually click the Log In Button and insert the credentials. The account logs in but the script then gets stuck in an endless loop or ends the session instantly.
 This might help for figuring out a solution.

Happy to contribute. Regards to Everybody.

**Comment by andreescocard** [comment]
Switch to dev branch, should fix your issue

**Comment by depayem** [comment]
> Switch to dev branch, should fix your issue

Ok, how do we do a dev branch install ?

**Comment by Tr1pke** [comment]
> > Switch to dev branch, should fix your issue
> 
> Ok, how do we do a dev branch install ?

 pip install -U git+https://github.com/timgrossmann/InstaPy@dev

**Comment by Flaunkerton2395** [comment]
Mine works now! I got a suspicious attempt screen though, is there any way around it?

**Comment by Flaunkerton2395** [comment]
Fixed it!

**Comment by depayem** [comment]
>Switch to dev branch, should fix your issue

>pip install -U git+https://github.com/timgrossmann/InstaPy@dev

Worked Guys! @Tr1pke  @andreescocard  Thank you!!

**Comment by Alexjpinto** [comment]
> > > Switch to dev branch, should fix your issue
> > 
> > 
> > Ok, how do we do a dev branch install ?
> 
> pip install -U git+https://github.com/timgrossmann/InstaPy@dev

Didn't Work for me, still the same error, im using DigitalOcean

**Comment by Aarxn31** [comment]
`INFO [2023-07-02 16:47:12] [xxxxxxx] - Cookie file not found, creating cookie...WARNING [2023-07-02 16:47:23] [xxxxxx] Login A/B test detected! Trying another string...WARNING [2023-07-02 16:47:28] [xxxxxxx] Could not pass the login A/B test. Trying last string...ERROR [2023-07-02 16:47:33] [xxxxxxx] Login A/B test failed!`

How do I fix this???

**Comment by tjnyland** [comment]
> `INFO [2023-07-02 16:47:12] [xxxxxxx] - Cookie file not found, creating cookie...WARNING [2023-07-02 16:47:23] [xxxxxx] Login A/B test detected! Trying another string...WARNING [2023-07-02 16:47:28] [xxxxxxx] Could not pass the login A/B test. Trying last string...ERROR [2023-07-02 16:47:33] [xxxxxxx] Login A/B test failed!`
> 
> this appears on the powershell. How do I fix it?

I have the same error
