### ISSUE TITLE
--> Invalid Like Element! in Version 0.6.9

### ISSUE THREAD

**Issue by taoye99** [InstaPy/InstaPy#5623]
## Expected Behavior
should return "--> Image Liked!"
## Current Behavior
return "--> Invalid Like Element!"
In like_util.py,
Debugged to line: browser.find_elements_by_xpath(like_xpath), but return empty list
## InstaPy configuration
new installation of 0.6.9 and Firefox 78.0.2 (64-bit)

**Comment by SRAlexander** [comment]
This was just solved here... https://github.com/timgrossmann/InstaPy/issues/5620

**Comment by taoye99** [comment]
I just downloaded the lastest version, still the same issue: Debugged to line: browser.find_elements_by_xpath(like_xpath) at line 751, but return empty list

**Comment by Booleboole** [comment]
Same problem for me
