### ISSUE TITLE
</button> is not clickable at point (688, 14)

### ISSUE THREAD

**Issue by kushpvo** [InstaPy/InstaPy#582]
Getting this error frequently these days after about 50 pictures on the first tag itself.
Running it on Vultr 2GB server.

`Traceback (most recent call last):
  File "quickstart.py", line 27, in <module>
    session.like_by_tags(['#houston', 'losangeles', 'neworleans'], amount=randint(minTag, maxTag))
  File "/root/InstaPy/instapy/instapy.py", line 539, in like_by_tags
    followed += follow_user(self.browser, self.follow_restrict, self.username, user_name)
  File "/root/InstaPy/instapy/unfollow_util.py", line 140, in follow_user
    follow_button.click()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 72, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webelement.py", line 461, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <button class="_qv64e _gexxb _4tgw8 _njrw0">...</button> is not clickable at point (688, 14). Other element w$
  (Session info: chrome=60.0.3112.101)
  (Driver info: chromedriver=2.29.461571 (8a88bbe0775e2a23afda0ceaf2ef7ee74e822cc5),platform=Linux 4.10.0-28-generic x86_64)
`

**Comment by kushpvo** [comment]
I guess i might have found a solution.
The follow button currently shows button class of `_qv64e _gexxb _r9b8f _njrw0`
while, the bot has button class of `_qv64e _gexxb _4tgw8 _njrw0`

Changing this might solve? I don't know how to change so someone could help me out here

**Comment by Jayphen** [comment]
I have the same issue. I think this is resolved by ensuring the browser scrolls to the top before sending the click to `follow_button`. Within `instapy/unfollow_util.py` I moved the `send_keys(Keys.HOME)` call to inside the if block and no longer have the issue.

**Comment by Jayphen** [comment]
#563 appears to fix this. Seems to be related to the actual button being obscured by some other element in the DOM, so `click()` does not work.

**Comment by kushpvo** [comment]
I did a `git pull` before testing the bot, but it still shows the same error. 
Am i missing something here?

**Comment by Jayphen** [comment]
#563 hasn't been merged yet, that's why.

**Comment by iSimonWeb** [comment]
I'm noticing here that we're referencing to a button via its preprocessed and abstract className.
Can't we instead target it by its position in the page? Eitherway we should change the class in the InstaPy code each time they update their platform.

Am I wrong?

**Comment by Jayphen** [comment]
@iSimonWeb If you check the code it actually uses xpath. Not sure where the classnames are coming from tbh. I think the reference to classnames in the traceback is a bit of a red herring – I suspect the issue is related to the element not being onscreen at the time of the `click` being fired.

**Comment by iSimonWeb** [comment]
@Jayphen thanks for the quick response.
Great then, the referenced pull request seems to solve it!

**Comment by dilee716** [comment]
@timgrossmann can we merge [#563](https://github.com/timgrossmann/InstaPy/pull/563) for the fix? It's already approved. Thanks!

**Comment by iSimonWeb** [comment]
No, wait, I think I have a simple solution with my pull request #587.

**Comment by kushpvo** [comment]
#564 does solve the problem. Thanks

**Comment by timgrossmann** [comment]
@dilee716 Well, it doesn't really make a lot of sense to have this change only made here...
It would be way better if @westondeboer could replace all the `.clicks()` with this method.

**Comment by iSimonWeb** [comment]
I've tested the code from my pull request #587 and the click error goes away.
Anyway sometimes the chrome page crash, could this be a problem due to the outdated Selenium version?
