### ISSUE TITLE
'!	~user is inaccessible - Bot Cannot follow!

### ISSUE THREAD

**Issue by rexonat** [InstaPy/InstaPy#5900]
**## Expected Behavior**

The bot should be following users from a list.

**## Current Behavior**
Cannot follow - getting error '~user is inaccessible' for all users. Have tried with usernames & account numbers. The text file with the list is formatted correctly.

```
root@test4:~/instapy-quickstart# python3 quickstart.py
InstaPy Version: 0.6.12
 ._.  ._.  ._.  ._.  ._.  ._.  ._. 
Workspace in use: "/root/InstaPy"
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
INFO [2020-11-15 11:20:45] [username]  Session started!
oooooooooooooooooooooooooooooooooooooooooooooooooooooo
WARNING [2020-11-15 11:22:11] [username]  --> Couldn't follow '3949224551'!	~user is inaccessibleusername
WARNING [2020-11-15 11:23:40] [username]  --> Couldn't follow 'cristiano'!	~user is inaccessible
WARNING [2020-11-15 11:25:08] [username]  --> Couldn't follow 'therock'!	~user is inaccessible
WARNING [2020-11-15 11:26:35] [username]  --> Couldn't follow 'kyliejenner'!	~user is inaccessible
WARNING [2020-11-15 11:28:02] [username]  --> Couldn't follow 'selenagomez'!	~user is inaccessible
WARNING [2020-11-15 11:29:28] [username]  --> Couldn't follow 'kimkardashian'!	~user is inaccessible
WARNING [2020-11-15 11:30:55] [username]  --> Couldn't follow 'leomessi'!	~user is inaccessible
WARNING [2020-11-15 11:32:21] [username]  --> Couldn't follow 'beyonce'!	~user is inaccessible
WARNING [2020-11-15 11:33:49] [username]  --> Couldn't follow 'natgeo'!	~user is inaccessible
WARNING [2020-11-15 11:35:15] [username]  --> Couldn't follow 'neymarjr'!	~user is inaccessible
WARNING [2020-11-15 11:36:43] [username]  --> Couldn't follow 'kendalljenner'!	~user is inaccessible
INFO [2020-11-15 11:36:46] [username]  Finished following by List!
```

**## InstaPy configuration**
OS: Ubuntu 18.04 x64 
InstaPy Version: 0.6.12
Python version:3.6.9
Mozilla Firefox 82.0.3
Geckodriver:0.1.0

Below is my Very basic quickstart file:

```
GNU nano 2.9.3                                     quickstart.py                                     Modified  

# imports
from instapy import InstaPy
from instapy import smart_run

# login credentials
insta_username = 'xxxx'
insta_password = 'xxxx'

# get an InstaPy session!
# set headless_browser=True to run InstaPy in the background
session = InstaPy(username=insta_username,
                  password=insta_password, 
                 headless_browser=True,
                bypass_security_challenge_using='sms')


# Follow the followers of each given user
list1 = session.target_list("./apples.txt")
session.follow_by_list(list1)
```

**Comment by fintzd** [comment]
Have you checked this issue #5526 ? Seems to have been solved by @mhdakhtar8 !

**Comment by rexonat** [comment]
> Have you checked this issue #5526 ? Seems to have been solved by @mhdakhtar8 !

This is a different issue, but does link to the same issue which was not fixed. I have tried (https://github.com/timgrossmann/InstaPy/issues/5298) the fixes mentioned here and the problem persists.

**Comment by v0lumehi** [comment]
This was fixed in https://github.com/timgrossmann/InstaPy/pull/5894/commits/0ffb797aa81f18f3f87a01370745ea60d35d22d7 and is being reviewed at the moment

**Comment by danielcasanova12** [comment]
did anyone find a solution??
the above codes didn't work for me
same error : Couldn't follow 'search_user'! ~user is inaccessible
