### ISSUE TITLE
firefox_profile issue

### ISSUE THREAD

**Issue by jvftw** [InstaPy/InstaPy#6716]
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/USER/InstaPy"
Traceback (most recent call last):
  File "c:\Users\USER\Desktop\Stuff\instapy\quickstart.py", line 25, in <module>
    session = InstaPy(username=insta_username,
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instapy\instapy.py", line 330, in __init__
    self.browser, err_msg = set_selenium_local_session(
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\instapy\browser.py", line 123, in set_selenium_local_session
    browser = webdriver.Firefox(
TypeError: WebDriver.__init__() got an unexpected keyword argument 'firefox_profile'

**Comment by alirezaunix** [comment]
same issue!!

**Comment by lejtdan** [comment]
Same issue as well

**Comment by mk1995** [comment]
Its like instapy needs upgrade regarding browser.py as well.
Here I have fixed the issue as following:
    # firefox_profile.update_preferences() 
    firefox_options.profile = firefox_profile

    # prefer user path before downloaded one
    driver_path = geckodriver_path or get_geckodriver()
    ser = FirefoxService(executable_path=driver_path, log_path=geckodriver_log) # we can use webdriver manager as well
    browser = webdriver.Firefox(
        # firefox_profile=firefox_profile, # delete this line of code.
        service=ser,
        options=firefox_options,
    )

**Comment by mk1995** [comment]
> Its like instapy needs upgrade on browser.py as well. Here I have fixed the issue as following:
> 
> ```
> # firefox_profile.update_preferences() 
> firefox_options.profile = firefox_profile
> # prefer user path before downloaded one
> driver_path = geckodriver_path or get_geckodriver()
> ser = FirefoxService(executable_path=driver_path, log_path=geckodriver_log) # we can use webdriver manager as well
> browser = webdriver.Firefox(
>     # firefox_profile=firefox_profile, # delete this line of code.
>     service=ser,
>     options=firefox_options,
> )
> ```

**Comment by sekoakb** [comment]
still not working. leads to NameError: name 'FirefoxService' is not defined this time.

**Comment by EnkrateiaLucca** [comment]
> still not working. leads to NameError: name 'FirefoxService' is not defined this time.

Mine worked using this:
firefox_options.profile = firefox_profile
    # geckodriver log in specific user logfolder
    geckodriver_log = "{}geckodriver.log".format(logfolder)
    # prefer user path before downloaded one
    driver_path = geckodriver_path or get_geckodriver()
    firefox_options.executable_path=driver_path
    firefox_options.log_path=geckodriver_log
    
    browser = webdriver.Firefox(
        options=firefox_options,
    )

**Comment by asadullahqb** [comment]
I'm stuck on this same issue too.

**Comment by Xehia** [comment]
From Selenium4 firefox_profile is deprecated.
You can install selenium3 for an easy fix :)

```
pip uninstall selenium
pip install selenium==3.141.0
```
